name: 'nsw_weather_gold'
version: '1.0.0'
config-version: 2

# Matches the profile name in profiles.yml
profile: 'nsw_weather_gold'

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  nsw_weather_gold:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: gold
